### ISSUE TITLE
Fail with a `.finished` event with proper message and status if initcontainer fails

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn-contrib/job-executor-service#124]
Right now initcontainer fails when it cannot fetch a file from configuration-service.

For instance, I have this config:
```
apiVersion: v2
actions:
  - name: "Run JMeter"
    events:
      - name: "sh.keptn.event.test.triggered"
        jsonpath:
          property: "$.data.test.teststrategy"
          match: "functional"
      - name: "sh.keptn.event.test.triggered"
        jsonpath:
          property: "$.data.test.teststrategy"
          match: "performance"
    tasks:
      - name: "Run jmeter smoke tests"
        files:
          - jmeter/basiccheck.jmx
          - jmeter/load.jmx
        image: "docker.io/christiankreuzbergerdtx/jmeter:latest"
        ...
```

but unfortunately initcontainer fails with
```
2021/12/17 10:31:18 Error while copying files: could not find file or directory jmeter/basiccheck.jmx for task Run jmeter smoke tests
```

In Keptn Bridge we only get this message:
```
11:31 job-executor-service finished with result fail

Job job-executor-service-job-855e19ed-baed-48b3-973e-0e62-1 failed: job job-executor-service-job-855e19ed-baed-48b3-973e-0e62-1 failed. Reason: BackoffLimitExceeded, Message: Job has reached the specified backoff limit
```

# Definition of Done

- [ ] Keptn Bridge shows the proper error message, e.g., `could not find file or directory jmeter/basiccheck.jmx for task`
