### ISSUE TITLE
Add support for imagePullPolicy

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn-contrib/job-executor-service#127]
Please add support for `imagePullPolicy` for Kubernetes Jobs - see https://kubernetes.io/docs/concepts/containers/images/#image-pull-policy for details.

**Example**:

```
apiVersion: v2
actions:
  - name: "Run locust"
    events: ...
    tasks:
      - name: "Run locust tests"
        files:
          - locust/basic.py
          - locust/import.py
          - locust/locust.conf
        image: "locustio/locust"
        imagePullPolicy: "Always"
        cmd:
          - locust
```

Please adhere to the [Default IMage pull policy](https://kubernetes.io/docs/concepts/containers/images/#imagepullpolicy-defaulting) by Kubernetes.

# Definition of Done

- [ ] Image Pull Policy field has been added in code
- [ ] README.md contains infos about this field
