### ISSUE TITLE
Add a "Minimalistic Getting started" example using alpine

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn-contrib/job-executor-service#141]
One of the first things that users will look for when trying to create their own config files for job-executor-service is an example that is as simple as showing the files that you have access to.

I've created such an example by listing files using alpine:

```
apiVersion: v2
actions:
  - name: "Fake Deployment"
    events:
      - name: "sh.keptn.event.deployment.triggered"
    tasks:
      - name: "List files"
        files:
          - /
        image: "alpine:3.15"
        cmd:
          - "ls"
        args:
         - "-la"
         - "/keptn"
```

# Definition of Done

- [ ] Added this example to README.md as a starting point
