### ISSUE TITLE
Create a minimalistic integration test

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn-contrib/job-executor-service#142]
Based on the example in #141, 

```
apiVersion: v2
actions:
  - name: "Fake Deployment"
    events:
      - name: "sh.keptn.event.my-task.triggered"
    tasks:
      - name: "List files"
        files:
          - /
        image: "alpine:3.15"
        cmd:
          - "ls"
        args:
         - "-la"
         - "/keptn"
 ```

a very simple integration test should be created:

1. Install K3s or K3d
2. Install Keptn in a specific version
3. Install job-executor-service from current branch (e.g., `helm install ./chart` --set ...)
4. Create a simple project with a simple shipyard (containing a sequence with task "my-task")
5. Upload the above config file for job-executor-service
6. Trigger this sequence
7. Validate that a job/pod/... has been created
8. Validate the my-task.finished event and its content

I'm aware that we don't have integration tests yet, so we will also use this story to prepare an easy integration test setup based on what Keptn core uses:

https://github.com/keptn/keptn/blob/05d8eb57b122111948daa47481875ee3b999d726/.github/workflows/integration_tests.yml#L246-L257

```bash
curl -sL https://get.keptn.sh | KEPTN_VERSION=0.11.2 bash
keptn install ...
```

```bash
helm install -n keptn job-executor-service chart/ --set image=...
```

https://github.com/keptn/keptn/blob/05d8eb57b122111948daa47481875ee3b999d726/.github/workflows/integration_tests.yml#L507-L515

# Definition of Done

- [ ] Simple integration test workflow created
- [ ] Integration test for minimalistic "ls -la /keptn" scenario created in Go
