### ISSUE TITLE
Allow specifying serviceAccount for jobs

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn-contrib/job-executor-service#144]
Right now job-executor-service needs the following permissions on Kubernetes (see https://github.com/keptn-contrib/job-executor-service/blob/main/chart/templates/serviceaccount.yaml for details):

* get, list, watch **secrets**
* `*` on pods, logs, persistent volume claims, jobs
* `*` on jobs

This allows job-executor-service to do its job (pun intended). However, what if an end-users wants to have a job that requires access to the Kubernetes API in a certain namespace, e.g.,
```
  - name: "Deploy using helm"
    events:
      - name: "sh.keptn.event.je-deployment.triggered"
    tasks:
      - name: "deploy"
        files:
          - /charts
        image: "alpine/helm:3.7.2"
        cmd:
          - helm
        args:
          - "install"
          - "--namespace"
          - "$(PROJECT)-$(STAGE)"
          - "$(SERVICE)"
          - "/keptn/charts/$(SERVICE).tgz"
        env:
          - name: PROJECT
            value: "$.data.project"
            valueFrom: event
          - name: STAGE
            value: "$.data.stage"
            valueFrom: event
          - name: SERVICE
            value: "$.data.service"
            valueFrom: event
```

We end up running in an error, e.g.:
```
Error: INSTALLATION FAILED: Kubernetes cluster unreachable: Get "http://localhost:8080/version?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
```
The reason behind this is simple: When launching jobs, those jobs cannot access the Kubernetes API, as the job is created with `AutomountServiceAccountToken: false`.

# Feature request / Proposal

## Provide possibility to specify serviceAccount per job

Example:
```
  - name: "Deploy using helm"
    events:
      - name: "sh.keptn.event.je-deployment.triggered"
    tasks:
      - name: "deploy"
        files:
          - /charts
        image: "alpine/helm:3.7.2"
        serviceAccount: "my-service-account" <<<<<<<
        cmd:
          - helm
        ...
```
*Note*: The end-user is responsible for creating and managing this SA.

## Provide possibility to define default serviceAccount for job-executor-service jobs

One would also want to specify a default service account for jobs via an environment variable / helm value, e.g.:

```
helm upgrade --install -n keptn job-executor-service https://github.com/keptn-contrib/job-executor-service/releases/download/x.y.z/job-executor-service-x.y.z.tgz --set job.defaultServiceAccount=my-service-account
```

**TO BE DISCUSSED**

**Comment by christian-kreuzberger-dtx** [comment]
Thomas has already made a small POC for this:

1. Create a cluster role binding, e.g.:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: keptn-job-executor-service-allow-edit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - kind: ServiceAccount
    name: job-executor-service
    namespace: keptn
```
2. Update code to allow specifying `ServiceAccountName` and set `automountServiceAccountToken` to `true`
```
diff --git a/pkg/k8sutils/job.go b/pkg/k8sutils/job.go
index 1af586c..e12de84 100644
--- a/pkg/k8sutils/job.go
+++ b/pkg/k8sutils/job.go
@@ -66,7 +66,7 @@ func (k8s *k8sImpl) CreateK8sJob(jobName string, action *config.Action, task con
                Medium:    v1.StorageMediumDefault,
                SizeLimit: &quantity,
        }
-       automountServiceAccountToken := false
+       automountServiceAccountToken := true

        runAsNonRoot := true
        convert := func(s int64) *int64 {
@@ -163,6 +163,7 @@ func (k8s *k8sImpl) CreateK8sJob(jobName string, action *config.Action, task con
                                                },
                                        },
                                        AutomountServiceAccountToken: &automountServiceAccountToken,
+                                       ServiceAccountName: "job-executor-service",
                                },
                        },
                        BackoffLimit: &backOffLimit,
```
