### ISSUE TITLE
Automatically add labels to job environment variables

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn-contrib/job-executor-service#184]
As a user, I want to use project, service and stage, as well as labels as environment variables without having to specify them in my job config. 

*Note*: KEPTN_PROJECT, KEPTN_SERVICE, KEPTN_STAGE are already part of job env (but it's not documented in FEATURES.md): 
https://github.com/keptn-contrib/job-executor-service/blob/38c9f19886251b5bbdd06a6391db1c146d90ce29/pkg/k8sutils/job.go#L270-L283

*Example Cloud Event:*
```json
{
  "data": {
    "configurationChange": {
      "values": {
        "image": "ghcr.io/christian-kreuzberger-dtx/my-awesome-project:0.0.2-dev.202202212056"
      }
    },
    "labels": {
      "app-version": "0.0.2",
      "build-datetime": "202202212056"
    },
    "message": "",
    "project": "my-awesome-project",
    "result": "pass",
    "service": "foobar",
    "stage": "production",
    "status": "succeeded"
  },
  "id": "10007730-5703-41f9-851d-6b50198bf61c",
  "source": "shipyard-controller",
  "specversion": "1.0",
  "time": "2022-02-21T20:57:31.773Z",
  "type": "sh.keptn.event.deployment.triggered",
  "shkeptncontext": "e13175ca-e6e7-4240-a08c-c6c1409ded06",
  "shkeptnspecversion": "0.2.3"
}
```

*Example Job Config*:
```yaml
apiVersion: v2
actions:
  - name: "Deploy using helm"
    events:
      - name: "sh.keptn.event.je-deployment.triggered"
    tasks:
      - name: "Run helm"
        files:
          - /charts
        env:
          - name: IMAGE
            value: "$.data.configurationChange.values.image"
            valueFrom: event
        image: "alpine/helm:3.7.2"
        cmd: ["helm"]
        args: ["upgrade", "--create-namespace", "--install", "-n", "$(KEPTN_PROJECT)-$(KEPTN_STAGE)", "$(KEPTN_SERVICE)", "/keptn/charts/$(KEPTN_SERVICE).tgz", "--set", "image=$(IMAGE)", "--wait"]

```

*Expected environment variables* (based on CloudEvent):

* `KEPTN_PROJECT` = my-awesome-project
* `KEPTN_SERVICE` = foobar
* `KEPTN_STAGE` = dev
* `LABELS_APP_VERSION` = 0.0.2
* `LABELS_BUILD_DATETIME` = 202202212056

**Definition of Done**:

* [ ] Labels can be used as environment variables, e.g., `$LABELS_KEY` (`-` replaced by `_`, everything uppercased)
* [ ] project, service, stage are available as environment variables, e.g., `$KEPTN_PROJECT`, `$KEPTN_SERVICE`, `$KEPTN_STAGE`
* [ ] FEATURES.md updated
