### ISSUE TITLE
job not triggered at `sh.keptn.event.deployment.triggered`

### ISSUE THREAD

**Issue by RoadRunnr** [keptn-contrib/job-executor-service#206]
I have job description:
```
apiVersion: v2
actions:
  - name: "Run something"
    events:
      - name: "sh.keptn.event.deployment.triggered"
    tasks:
      - name: "Deploy Something"
        files:
          - deploy.sh
          - networks.yaml
        image: "bitnami/kubectl:latest"
        cmd:
          - ls -la
```

However, this job is not triggered at all when the service is deployed.
A log of the distributor container in the job-executor-service shows other triggers, but none for any deployment.

keptn 0.13.4 and jes 0.1.8-next.3

**Comment by Raffy23** [comment]
Hi, it seems that your job configuration isn't valid. The command given in `cmd` must only be the executable and all arguments must go into the `args` property. Your task should look like this: 
```yaml
    tasks:
      - name: "Greet the world"
        image: "bitnami/kubectl:latest"
        cmd:
          - ls
        args:
          - "-la"
```

But that should already emit a failing job, which you can check via kubectl (`kubectl -n <namespace> get jobs`) and should also produce some error messages similar to the one shown below: 
```
[job-executor-service] 2022/03/29 11:26:04 Error while creating job: job job-executor-service-job-a83c4fef-9ff2-454f-9b61-83e4-1 failed. Reason: BackoffLimitExceeded, Message: Job has reached the specified backoff limit
[distributor] time="2022-03-29T11:26:04Z" level=info msg="Received CloudEvent with ID 30070846-0103-44e1-9e9f-5c55b326f8ad - Forwarding to Keptn"
[distributor] time="2022-03-29T11:26:04Z" level=info msg="Received '.finished' event with status 'errored'. Forwarding log message to log ingestion API"
[distributor] time="2022-03-29T11:26:04Z" level=info msg="Event forwarded successfully"
```

If that is not the case, please verify that the job-executor-service shows up correctly in the bridge (with all subscriptions you have configured) and that the job configuration was successfully added via `keptn add-resource` to the repository.
