### ISSUE TITLE
Specifying non-existing Service Account leads to job not starting

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn-contrib/job-executor-service#234]
This was testedwith jes pre-release 0.2.0-next.0.

When specifying serviceAccount of a job, e.g.,

```
  - name: "Deploy using helm"
    events:
      - name: "sh.keptn.event.je-deployment.triggered"
    tasks:
      - name: "Run helm"
        files:
          - /charts
        env:
          - name: IMAGE
            value: "$.data.configurationChange.values.image"
            valueFrom: event
        image: "alpine/helm:3.7.2"
        serviceAccount: "jes-deploy-using-helm"
        cmd: ["helm"]
```

without `jes-deploy-using-helm` existing in the current namespace, the job is not starting (and eventually times out).

# Expected Behaviour

There should be an error sent back to Keptn (either as a .finished event with status fail/error, or a dedicated error log).
