### ISSUE TITLE
Introduce waitFor parameter

### ISSUE THREAD

**Issue by agardnerIT** [keptn-contrib/job-executor-service#352]
As the job executor service is installed on a remote execution plane (ie. namespace other than `keptn` where the control plane components are installed), it can only listen for `.triggered` events.

However it would be beneficial to be able to `waitFor` the corresponding `.started` (or perhaps more realistically) the corresponding `.finished` event for the `.triggered` event.

Usecase
I want to send a CURL request when a `.finished` event has a `data.result == fail`. If `waitFor` was implemented, I could do something like this and it wouln't break the existing "contract" that remote exec plane services can only listen for triggered events.

1. Listen for evaluation.triggered. At this point we know the `shkeptncontext`, `triggeredid` and all details
2. Before running curl, poll keptn waiting for `evaluation.finished` event.
3. Once the finished event is available, pull it and run curl IF the `data.result` matches `fail`.

```
  - name: "Notify Failed Evaluation"
    events:
      - name: "sh.keptn.event.evaluation.triggered"
        waitFor: "finished"
        silent: true
        jsonpath:
          property: "$.data.result"
            match: "fail"
    tasks:
      - name: "Push notification on evalution failure"
        image: "curl/curl:0.0.1"
        cmd:
          - "curl"
          - "-X"
          - "POST"
          - "https://example.com"
          - "--data-raw"
          - "{ \"foo\": \"bar\" }"
```
