### ISSUE TITLE
Metadata aware executions

### ISSUE THREAD

**Issue by agardnerIT** [keptn-contrib/job-executor-service#363]
I know the event filtering is possible, but that's a global setting. It applies to all installed JES instances that are attached to a single control plane.

Is it possible to leverage metadata in triggered events (or some other property) to conditionally execute different JES installs in the same project + service + stage combination?

For example, imagine I have 3 clusters globally all listening for `test.triggered` and I wish to only load test on the `europe` cluster. I might pass in some property like `data.test.location` and then my JES could filter for:

```
tasks:
  - name: "Run locust tests"
    jsonpath:
      property: "$.data.test.location"
      match: "europe"
    files:
      - locust/basic.py
      - locust/import.py
      - locust/locust.conf
    image: "locustio/locust"
    cmd:
      - locust
    args:
      - '--config'
      - /keptn/locust/locust.conf
      - '-f'
      - /keptn/locust/basic.py
      - '--host'
      - $(HOST)
```

![image](https://user-images.githubusercontent.com/26523841/191134022-1e3c8ee9-b0ac-4053-a659-80ecfa8b89d9.png)
