### ISSUE TITLE
Add support for ttlSecondsAfterFinished to cleanup completed jobs

### ISSUE THREAD

**Issue by donovanmuller** [keptn-contrib/job-executor-service#44]
Over time you can end up with many Jobs in the `Completed` status. It would be handy to be able to enable optional support for [`ttlSecondsAfterFinished`](https://kubernetes.io/docs/concepts/workloads/controllers/job/#clean-up-finished-jobs-automatically) to cleanup these Jobs. This is a beta feature in Kubernetes 1.21 and alpha before that (available as an enabled alpha feature in the EKS 1.20 [release](https://aws.amazon.com/blogs/containers/amazon-eks-1-20-released/)).

This feature might be added as a controller argument to enable the feature but that is disabled by default.

**Comment by didiladi** [comment]
@donovanmuller that's a great idea! Thanks for opening this issue! :rocket:

**Comment by TannerGabriel** [comment]
@didiladi I could take this issue on.

**Comment by TannerGabriel** [comment]
Where should we define the `ttlSecondsAfterFinished` parameter in the YAML definition?

Example (defined under tasks key):

```
apiVersion: v2
actions:
  - name: "Print files"
    events:
      - name: "sh.keptn.event.sample.triggered"
    tasks:
      - name: "Show files in bin"
        image: "alpine"
        workingDir: "/bin"
        cmd:
          - ls
        ttlSecondsAfterFinished: 60
```
